import type { UniverseItem } from "./types";

export const universeItems: UniverseItem[] = [
  // Words (10 items)
  {
    id: "word-1",
    type: "word",
    content: "coffee",
    x: 12,
    y: 18,
    rotation: -8,
    delay: 0,
    duration: 4.2,
  },
  {
    id: "word-2",
    type: "word",
    content: "plans",
    x: 76,
    y: 14,
    rotation: 5,
    delay: 0.4,
    duration: 3.8,
  },
  {
    id: "word-3",
    type: "word",
    content: "focus",
    x: 22,
    y: 68,
    rotation: 6,
    delay: 0.7,
    duration: 4.5,
  },
  {
    id: "word-4",
    type: "word",
    content: "weekend",
    x: 69,
    y: 74,
    rotation: -5,
    delay: 0.2,
    duration: 3.6,
  },
  {
    id: "word-5",
    type: "word",
    content: "future",
    x: 48,
    y: 20,
    rotation: -3,
    delay: 0.9,
    duration: 4.8,
  },
  {
    id: "word-6",
    type: "word",
    content: "balance",
    x: 85,
    y: 45,
    rotation: 7,
    delay: 0.6,
    duration: 4.1,
  },
  {
    id: "word-7",
    type: "word",
    content: "clarity",
    x: 8,
    y: 55,
    rotation: -7,
    delay: 0.3,
    duration: 3.9,
  },
  {
    id: "word-8",
    type: "word",
    content: "freedom",
    x: 55,
    y: 5,
    rotation: 4,
    delay: 0.8,
    duration: 4.4,
  },
  {
    id: "word-9",
    type: "word",
    content: "growth",
    x: 93,
    y: 75,
    rotation: -6,
    delay: 0.5,
    duration: 4.6,
  },
  {
    id: "word-10",
    type: "word",
    content: "peace",
    x: 30,
    y: 40,
    rotation: 3,
    delay: 0.1,
    duration: 3.7,
  },

  // Numbers (10 items)
  {
    id: "number-1",
    type: "number",
    content: "$2,450",
    x: 10,
    y: 43,
    rotation: -6,
    delay: 0.3,
    duration: 4.1,
  },
  {
    id: "number-2",
    type: "number",
    content: "$-84.20",
    x: 81,
    y: 39,
    rotation: 4,
    delay: 0.8,
    duration: 3.9,
  },
  {
    id: "number-3",
    type: "number",
    content: "$1,200",
    x: 37,
    y: 82,
    rotation: 3,
    delay: 0.5,
    duration: 4.4,
  },
  {
    id: "number-4",
    type: "number",
    content: "$7,890",
    x: 69,
    y: 31,
    rotation: -5,
    delay: 0.2,
    duration: 4.7,
  },
  {
    id: "number-5",
    type: "number",
    content: "$-156.30",
    x: 18,
    y: 76,
    rotation: 6,
    delay: 0.9,
    duration: 3.5,
  },
  {
    id: "number-6",
    type: "number",
    content: "$3,450",
    x: 73,
    y: 20,
    rotation: -4,
    delay: 0.4,
    duration: 4.2,
  },
  {
    id: "number-7",
    type: "number",
    content: "$-22.50",
    x: 75,
    y: 45,
    rotation: 5,
    delay: 0.7,
    duration: 3.8,
  },
  {
    id: "number-8",
    type: "number",
    content: "$9,200",
    x: 5,
    y: 32,
    rotation: -3,
    delay: 0.1,
    duration: 4.5,
  },
  {
    id: "number-9",
    type: "number",
    content: "$-310.00",
    x: 73,
    y: 55,
    rotation: 7,
    delay: 0.6,
    duration: 3.6,
  },
  {
    id: "number-10",
    type: "number",
    content: "$5,100",
    x: 55,
    y: 92,
    rotation: -5,
    delay: 0.8,
    duration: 4.3,
  },

  // Income (10 items)
  {
    id: "income-1",
    type: "income",
    content: "+$2,400 income",
    x: 58,
    y: 10,
    rotation: -4,
    delay: 0.5,
    duration: 4,
  },
  {
    id: "income-2",
    type: "income",
    content: "+$150 freelance",
    x: 15,
    y: 9,
    rotation: 3,
    delay: 0.2,
    duration: 3.7,
  },
  {
    id: "income-3",
    type: "income",
    content: "+$80 dividends",
    x: 90,
    y: 68,
    rotation: -6,
    delay: 0.9,
    duration: 4.5,
  },
  {
    id: "income-4",
    type: "income",
    content: "+$450 bonus",
    x: 40,
    y: 22,
    rotation: 5,
    delay: 0.4,
    duration: 3.9,
  },
  {
    id: "income-5",
    type: "income",
    content: "+$1,200 rental",
    x: 70,
    y: 85,
    rotation: -3,
    delay: 0.7,
    duration: 4.2,
  },
  {
    id: "income-6",
    type: "income",
    content: "+$60 interest",
    x: 28,
    y: 52,
    rotation: 4,
    delay: 0.1,
    duration: 3.6,
  },
  {
    id: "income-7",
    type: "income",
    content: "+$950 side gig",
    x: 84,
    y: 24,
    rotation: -7,
    delay: 0.6,
    duration: 4.8,
  },
  {
    id: "income-8",
    type: "income",
    content: "+$200 gift",
    x: 55,
    y: 20,
    rotation: 6,
    delay: 0.3,
    duration: 4.1,
  },
  {
    id: "income-9",
    type: "income",
    content: "+$3,100 salary",
    x: 8,
    y: 88,
    rotation: -4,
    delay: 0.8,
    duration: 3.5,
  },
  {
    id: "income-10",
    type: "income",
    content: "+$75 cashback",
    x: 60,
    y: 85,
    rotation: 3,
    delay: 0.5,
    duration: 4.4,
  },

  // Debt (10 items)
  {
    id: "debt-1",
    type: "debt",
    content: "$3,200 debt",
    x: 82,
    y: 61,
    rotation: 6,
    delay: 0.1,
    duration: 4.7,
  },
  {
    id: "debt-2",
    type: "debt",
    content: "$1,500 card",
    x: 32,
    y: 13,
    rotation: -5,
    delay: 0.6,
    duration: 3.8,
  },
  {
    id: "debt-3",
    type: "debt",
    content: "$900 medical",
    x: 63,
    y: 16,
    rotation: 4,
    delay: 0.3,
    duration: 4.3,
  },
  {
    id: "debt-4",
    type: "debt",
    content: "$12,000 loan",
    x: 20,
    y: 38,
    rotation: -7,
    delay: 0.8,
    duration: 3.6,
  },
  {
    id: "debt-5",
    type: "debt",
    content: "$250 overdue",
    x: 87,
    y: 82,
    rotation: 5,
    delay: 0.4,
    duration: 4.5,
  },
  {
    id: "debt-6",
    type: "debt",
    content: "$600 utility",
    x: 44,
    y: 15,
    rotation: -3,
    delay: 0.9,
    duration: 3.9,
  },
  {
    id: "debt-7",
    type: "debt",
    content: "$4,800 student",
    x: 9,
    y: 67,
    rotation: 7,
    delay: 0.2,
    duration: 4.1,
  },
  {
    id: "debt-8",
    type: "debt",
    content: "$350 phone",
    x: 76,
    y: 33,
    rotation: -6,
    delay: 0.5,
    duration: 3.7,
  },
  {
    id: "debt-9",
    type: "debt",
    content: "$1,800 tax",
    x: 50,
    y: 95,
    rotation: 4,
    delay: 0.7,
    duration: 4.4,
  },
  {
    id: "debt-10",
    type: "debt",
    content: "$100 late fee",
    x: 38,
    y: 92,
    rotation: -4,
    delay: 0.1,
    duration: 3.5,
  },

  // Tasks (10 items)
  {
    id: "task-1",
    type: "task",
    content: "Review subscriptions",
    x: 17,
    y: 84,
    rotation: -4,
    delay: 0.6,
    duration: 3.8,
  },
  {
    id: "task-2",
    type: "task",
    content: "Plan next month",
    x: 73,
    y: 87,
    rotation: 4,
    delay: 0.3,
    duration: 4.2,
  },
  {
    id: "task-3",
    type: "task",
    content: "Save for Japan",
    x: 30,
    y: 90,
    rotation: -5,
    delay: 0.9,
    duration: 4.6,
  },
  {
    id: "task-4",
    type: "task",
    content: "Pay credit card",
    x: 91,
    y: 50,
    rotation: 6,
    delay: 0.2,
    duration: 3.9,
  },
  {
    id: "task-5",
    type: "task",
    content: "Invest $500",
    x: 30,
    y: 60,
    rotation: -3,
    delay: 0.7,
    duration: 4.3,
  },
  {
    id: "task-6",
    type: "task",
    content: "Update budget",
    x: 63,
    y: 20,
    rotation: 5,
    delay: 0.4,
    duration: 3.7,
  },
  {
    id: "task-7",
    type: "task",
    content: "Cancel gym",
    x: 15,
    y: 25,
    rotation: -6,
    delay: 0.8,
    duration: 4.5,
  },
  {
    id: "task-8",
    type: "task",
    content: "Split expenses",
    x: 79,
    y: 70,
    rotation: 3,
    delay: 0.1,
    duration: 4.1,
  },
  {
    id: "task-9",
    type: "task",
    content: "Check 401k",
    x: 20,
    y: 48,
    rotation: -4,
    delay: 0.5,
    duration: 3.6,
  },
  {
    id: "task-10",
    type: "task",
    content: "Set emergency fund",
    x: 95,
    y: 38,
    rotation: 7,
    delay: 0.9,
    duration: 4.4,
  },

  // Transactions (10 items)
  {
    id: "transaction-1",
    type: "transaction",
    content: "Netflix · -$15.99",
    x: 28,
    y: 28,
    rotation: -3,
    delay: 0.4,
    duration: 4.3,
  },
  {
    id: "transaction-2",
    type: "transaction",
    content: "Salary · +$2,400",
    x: 82,
    y: 52,
    rotation: 5,
    delay: 0.7,
    duration: 3.7,
  },
  {
    id: "transaction-3",
    type: "transaction",
    content: "Coffee · -$8.40",
    x: 25,
    y: 20,
    rotation: -5,
    delay: 0.2,
    duration: 4.5,
  },
  {
    id: "transaction-4",
    type: "transaction",
    content: "Rent · -$1,200",
    x: 86,
    y: 17,
    rotation: 6,
    delay: 0.6,
    duration: 3.8,
  },
  {
    id: "transaction-5",
    type: "transaction",
    content: "Freelance · +$150",
    x: 24,
    y: 79,
    rotation: -7,
    delay: 0.3,
    duration: 4.2,
  },
  {
    id: "transaction-6",
    type: "transaction",
    content: "Uber · -$12.50",
    x: 72,
    y: 40,
    rotation: 4,
    delay: 0.9,
    duration: 3.5,
  },
  {
    id: "transaction-7",
    type: "transaction",
    content: "Bonus · +$450",
    x: 8,
    y: 15,
    rotation: -4,
    delay: 0.1,
    duration: 4.6,
  },
  {
    id: "transaction-8",
    type: "transaction",
    content: "Amazon · -$34.20",
    x: 74,
    y: 65,
    rotation: 5,
    delay: 0.5,
    duration: 4.0,
  },
  {
    id: "transaction-9",
    type: "transaction",
    content: "Gym · -$50.00",
    x: 45,
    y: 8,
    rotation: -6,
    delay: 0.8,
    duration: 3.9,
  },
  {
    id: "transaction-10",
    type: "transaction",
    content: "Dividend · +$80",
    x: 92,
    y: 58,
    rotation: 3,
    delay: 0.2,
    duration: 4.7,
  },

    // Mindful quotes/sentences (10 items - forming a cohesive text about mental order)
{
  id: "quote-1",
  type: "word",
  content: "When I consider how my light is spent",
  x: 15,
  y: 57,
  rotation: -2,
  delay: 0.3,
  duration: 5.0,
},
{
  id: "quote-2",
  type: "word",
  content: " Ere half my days in this dark world and wide,",
  x: 45,
  y: 90,
  rotation: 2,
  delay: 0.6,
  duration: 4.8,
},
{
  id: "quote-3",
  type: "word",
  content: " And that one talent which is death to hide",
  x: 2,
  y: 7,
  rotation: -1,
  delay: 0.9,
  duration: 5.2,
},
{
  id: "quote-4",
  type: "word",
  content: "Lodg’d with me useless, though my soul more bent",
  x: 32,
  y: 4,
  rotation: 1,
  delay: 1.2,
  duration: 4.6,
},
{
  id: "quote-5",
  type: "word",
  content: " To serve therewith my Maker, and present",
  x: 65,
  y: 90,
  rotation: -3,
  delay: 0.5,
  duration: 5.1,
},
{
  id: "quote-6",
  type: "word",
  content: " My true account, lest he returning chide,",
  x: 90,
  y: 30,
  rotation: 3,
  delay: 0.8,
  duration: 4.9,
},
{
  id: "quote-7",
  type: "word",
  content: " “Doth God exact day-labour, light denied?” ",
  x: 27,
  y: 70,
  rotation: -2,
  delay: 0.4,
  duration: 5.3,
},
{
  id: "quote-8",
  type: "word",
  content: "I fondly ask. But Patience, to prevent",
  x: 72,
  y: 80,
  rotation: 2,
  delay: 0.7,
  duration: 4.7,
},
];
